# Generated by Django 4.0 on 2022-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_profile_rename_post_user_post_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='time',
        ),
        migrations.AddField(
            model_name='user_post',
            name='caption',
            field=models.CharField(default=0.0005997001499250374, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_directory_path()'),
        ),
        migrations.AddField(
            model_name='user_post',
            name='slug',
            field=models.SlugField(default=0.0005997001499250374, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_post',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
