# Generated by Django 4.0.3 on 2022-04-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
